version: '3.8'
services:
  keycloak:
    build:
      dockerfile: keycloak.Dockerfile
    ports:
      - '8080:8080'
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=dsi31
    command: ['start-dev']
  discovery:
    image: haithemdridiweb/discovery-microservice:latest
    ports:
      - '8761:8761'
    depends_on:
      - keycloak
  gateway:
    image: haithemdridiweb/gateway-microservice:latest
    ports:
      - '8888:8888'
    depends_on:
      - discovery
  category:
    image: haithemdridiweb/category-microservice:latest
    ports:
      - '8081:8081'
    volumes:
      - category_uploads:/app/uploads
    depends_on:
      - gateway
  product:
    image: haithemdridiweb/product-microservice:latest
    ports:
      - '8082:8082'
    volumes:
      - product_uploads:/app/uploads
    depends_on:
      - category
  order:
    image: haithemdridiweb/order-microservice:latest
    ports:
      - '8090:8090'
    depends_on:
      - product
  trackshippement:
    image: haithemdridiweb/trackshippement-microservice:latest
    ports:
      - '8089:8089'
    depends_on:
      - order
  wishlist:
    image: haithemdridiweb/wishlist-microservice:latest
    ports:
      - '8084:8084'
    depends_on:
      - product
  auth:
    image: haithemdridiweb/auth-microservice:latest
    ports:
      - '8085:8085'
  notification:
    image: haithemdridiweb/notification-microservice:latest
    ports:
      - '8097:8097'
  news:
    image: haithemdridiweb/news-microservice:latest
    ports:
      - '8086:8086'
    volumes:
      - news_uploads:/app/uploads

  angular_client:
    image: haithemdridiweb/angular-client:latest
    ports:
      - "80:80"

  angular_admin:
    image: haithemdridiweb/angular-admin:latest
    ports:
      - "80:81"

volumes:
  category_uploads:
  product_uploads:
  news_uploads:
