name: androidCICD
env:
  path: 'FrontEnd/MobileVersion'
on:
  push:
    branches:
      - main
    paths:
      - 'FrontEnd/MobileVersion/**'
  workflow_dispatch:
jobs:
  buildAndroid:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'
      - name: Change wrapper permissions
        run: |
          cd ${{ env.path }} 
          chmod +x ./gradlew
      - name: Build gradle project
        run: |
          cd ${{ env.path }}
          ./gradlew build --warning-mode=all
      - name: Build apk release project (APK)
        run: |
          cd ${{ env.path }}
          ./gradlew assemble
      - name: Upload APK Release
        uses: actions/upload-artifact@v3
        with:
          name: APK
          path: ${{ env.path }}/app/build/outputs/apk/debug/app-debug.apk
      - name: Send Apk to server
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: 34.199.239.78
          username: haythem
          password: haythem
          server-dir: /home/haythem/APK/
          local-dir: ${{ env.path }}/app/build/outputs/apk/debug/
